USE [master]
GO

/****** Object:  Database [bearded_lama]    Script Date: 15/04/2014 1:52:36 PM ******/
CREATE DATABASE [bearded_lama]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bearded_lama', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\bearded_lama.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'bearded_lama_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\bearded_lama_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [bearded_lama] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bearded_lama].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bearded_lama] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bearded_lama] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bearded_lama] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bearded_lama] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bearded_lama] SET ARITHABORT OFF 
GO

ALTER DATABASE [bearded_lama] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bearded_lama] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [bearded_lama] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bearded_lama] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bearded_lama] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bearded_lama] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bearded_lama] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bearded_lama] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bearded_lama] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bearded_lama] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bearded_lama] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bearded_lama] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bearded_lama] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bearded_lama] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bearded_lama] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bearded_lama] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bearded_lama] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bearded_lama] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bearded_lama] SET RECOVERY FULL 
GO

ALTER DATABASE [bearded_lama] SET  MULTI_USER 
GO

ALTER DATABASE [bearded_lama] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bearded_lama] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bearded_lama] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bearded_lama] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [bearded_lama] SET  READ_WRITE 
GO


